version: '2'
services:
  poliactor_server:
    image: stelmachd/wb:poliaktor
    environment:
      FLASK_DEBUG: 1
      FLASK_ENV: development
      FLASK_APP: __init__.py
      LC_ALL: C.UTF-8
      LANG: C.UTF-8

    ports:
      - "6113:6113"
    volumes:
      - ../project/poliaktor_server:/app
    # entrypoint:
    #   - flask
    #   - run
    #   - --host=0.0.0.0