version: '3'
services:
  poliactor_server:
    image: stelmachd/wb:poliaktor_slim_noavx
    environment:
      FLASK_DEBUG: 1
      FLASK_ENV: development
      FLASK_APP: __init__.py
      LC_ALL: C.UTF-8
      LANG: C.UTF-8

    ports:
      - "8000:8000"
    volumes:
      - ../poliaktor_server:/app