version: '3'
services:
  poliactor_server:
    image: wb:poliaktor_slim
    environment:
      FLASK_DEBUG: 1
      FLASK_ENV: development
      FLASK_APP: __init__.py
      LC_ALL: C.UTF-8
      LANG: C.UTF-8

    ports:
      - "6113:6113"
    volumes:
      - ../poliaktor_server:/app